---
title: "Splicing Analysis"
author: "Daniel Guevara"
date: "2025-05-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1. Call libraries
```{r}
library(dplyr)
library(tidyr)
library(stringr)
library(ggplot2)
library(ggrepel)
library(patchwork)
library(pheatmap)
library(openxlsx)
library(OmicsKit)
```

# 2. Setup directories
```{r}
working_dir <- "~/github/HLA-I_Analysis/splicing"
setwd(working_dir)
```

# 3. Retrieve splicing results
```{r}
# JC model
res.SE.JC <- data.frame(read.csv("results/all_samples_variable_ind/output/SE.MATS.JC.txt", sep = "\t"))
res.SE.JC.sig <- res.SE.JC[res.SE.JC$FDR < 0.01 & abs(res.SE.JC$IncLevelDifference) >= 0.05, ]

res.MXE.JC <- data.frame(read.csv("results/all_samples_variable_ind/output/MXE.MATS.JC.txt", sep = "\t"))
res.MXE.JC.sig <- res.MXE.JC[res.MXE.JC$FDR < 0.01 & abs(res.MXE.JC$IncLevelDifference) >= 0.05, ]

res.RI.JC <- data.frame(read.csv("results/all_samples_variable_ind/output/RI.MATS.JC.txt", sep = "\t"))
res.RI.JC.sig <- res.RI.JC[res.RI.JC$FDR < 0.01 & abs(res.RI.JC$IncLevelDifference) >= 0.05, ]

res.A3SS.JC <- data.frame(read.csv("results/all_samples_variable_ind/output/A3SS.MATS.JC.txt", sep = "\t"))
res.A3SS.JC.sig <- res.A3SS.JC[res.A3SS.JC$FDR < 0.01 & abs(res.A3SS.JC$IncLevelDifference) >= 0.05, ]

res.A5SS.JC <- data.frame(read.csv("results/all_samples_variable_ind/output/A5SS.MATS.JC.txt", sep = "\t"))
res.A5SS.JC.sig <- res.A5SS.JC[res.A5SS.JC$FDR < 0.01 & abs(res.A5SS.JC$IncLevelDifference) >= 0.05, ]

# JCEC model
res.SE.JCEC <- data.frame(read.csv("results/all_samples_variable_ind/output/SE.MATS.JCEC.txt", sep = "\t"))
res.SE.JCEC.sig <- res.SE.JCEC[res.SE.JCEC$FDR < 0.01 & abs(res.SE.JCEC$IncLevelDifference) >= 0.05, ]

res.MXE.JCEC <- data.frame(read.csv("results/all_samples_variable_ind/output/MXE.MATS.JCEC.txt", sep = "\t"))
res.MXE.JCEC.sig <- res.MXE.JCEC[res.MXE.JCEC$FDR < 0.01 & abs(res.MXE.JCEC$IncLevelDifference) >= 0.05, ]

res.RI.JCEC <- data.frame(read.csv("results/all_samples_variable_ind/output/RI.MATS.JCEC.txt", sep = "\t"))
res.RI.JCEC.sig <- res.RI.JCEC[res.RI.JCEC$FDR < 0.01 & abs(res.RI.JCEC$IncLevelDifference) >= 0.05, ]

res.A3SS.JCEC <- data.frame(read.csv("results/all_samples_variable_ind/output/A3SS.MATS.JCEC.txt", sep = "\t"))
res.A3SS.JCEC.sig <- res.A3SS.JCEC[res.A3SS.JCEC$FDR < 0.01 & abs(res.A3SS.JCEC$IncLevelDifference) >= 0.05, ]

res.A5SS.JCEC <- data.frame(read.csv("results/all_samples_variable_ind/output/A5SS.MATS.JCEC.txt", sep = "\t"))
res.A5SS.JCEC.sig <- res.A5SS.JCEC[res.A5SS.JCEC$FDR < 0.01 & abs(res.A5SS.JCEC$IncLevelDifference) >= 0.05, ]
```

## 3.1 Correlation of count models
```{r}
psi_correlation <- function(df1, df2, columns = c("ID", "geneSymbol", "IncLevelDifference"),
                            cutoff = 0.4, title, p_size = 2.5, p_shape = 20)
{
  # Integrate data frames
  merged_df <- merge(df1[, columns], df2[, columns],
                     by = columns[1:2], suffixes = c("_JC", "_JCEC"))
  
  # Create label data frame
  label_df <- subset(merged_df,
                     abs(IncLevelDifference_JC) >= cutoff | abs(IncLevelDifference_JCEC) >= cutoff)
  
  label_df$nudge_y <- ifelse(label_df$IncLevelDifference_JCEC > label_df$IncLevelDifference_JC,
                             0.08, -0.08)
  
  # Pearson correlation
  cor_test <- cor.test(merged_df$IncLevelDifference_JC,
                       merged_df$IncLevelDifference_JCEC, method = "pearson")
  r_squared <- round(cor_test$estimate^2, 3)
  
  # Plotting
  plot <- ggplot(merged_df, aes(x = IncLevelDifference_JC, y = IncLevelDifference_JCEC)) +
    geom_smooth(method = "lm", se = FALSE, color = "red", linetype = "dashed") +
    geom_point(alpha = 0.7, size = p_size, shape = p_shape) + theme_bw() +
    annotate("text", x = 0.6, y = -0.6, label = paste0("R² = ", r_squared), size = 4, hjust = 0) +
    geom_label_repel(data = label_df, aes(label = geneSymbol), size = 3,
                     nudge_y = label_df$nudge_y, segment.alpha = 0.5, segment.size = 0.3,
                     box.padding = unit(0.4, "lines"), point.padding = unit(0.3, "lines"),
                     max.overlaps = Inf, show.legend = FALSE) +
    labs(title = title,
         x = expression(Delta*"PSI"*" - Junction Count"),
         y = expression(Delta*"PSI"*" - Junction & Exon Count")) +
    coord_cartesian(xlim = c(min(merged_df$IncLevelDifference_JC) - 0.1,
                             max(merged_df$IncLevelDifference_JC) + 0.1),
                    ylim = c(min(merged_df$IncLevelDifference_JCEC) - 0.1,
                             max(merged_df$IncLevelDifference_JCEC) + 0.1))
  
  return(plot)
}

psi_correlation(df1 = res.SE.JC.sig, df2 = res.SE.JCEC.sig, title = "Skipped Exon")
psi_correlation(df1 = res.MXE.JC.sig, df2 = res.MXE.JCEC.sig, title = "Mutually Exclusive Exons", cutoff = 0.3)
psi_correlation(df1 = res.RI.JC.sig, df2 = res.RI.JCEC.sig, title = "Retained Intron", cutoff = 0.3)
psi_correlation(df1 = res.A3SS.JC.sig, df2 = res.A3SS.JCEC.sig, title = "Alt. 3' Splice Sites", cutoff = 0.2)
psi_correlation(df1 = res.A5SS.JC.sig, df2 = res.A5SS.JCEC.sig, title = "Alt. 5' Splice Sites", cutoff = 0.2)


```

## 3.2 Detectable results
```{r}
# A) Plot counts
nice_Hist <- function(counts, mean = "Mean", thresholds = c(seq(0, 2, 0.5), 3, 5), xlim = 50, bin = 1, ytick = 2500) {
  levels_vector <- c(paste0("= ", thresholds[1]), paste0("<= ", thresholds[2]), paste0("<= ", thresholds[3]),
                     paste0("<= ", thresholds[4]), paste0("<= ", thresholds[5]), paste0("<= ", thresholds[6]),
                     paste0("<= ", thresholds[7]), paste0("> ", thresholds[7]))
  
  counts <- counts %>% mutate(category = case_when(.data[[mean]] == thresholds[1] ~ levels_vector[1],
                                                   .data[[mean]] <= thresholds[2] ~ levels_vector[2],
                                                   .data[[mean]] <= thresholds[3] ~ levels_vector[3],
                                                   .data[[mean]] <= thresholds[4] ~ levels_vector[4],
                                                   .data[[mean]] <= thresholds[5] ~ levels_vector[5],
                                                   .data[[mean]] <= thresholds[6] ~ levels_vector[6],
                                                   .data[[mean]] <= thresholds[7] ~ levels_vector[7],
                                                   TRUE ~ levels_vector[8]))
  
  counts$category <- factor(counts$category, levels = levels_vector)
  
  fill_colors <- setNames(c("#00004F", "#6000C6", "#B3A3FF", "steelblue", "#608FE6", "#85C0FF", "grey70", "white"), levels_vector)
  
  plot <- ggplot(counts[counts[[mean]] <= xlim, ], aes(x = .data[[mean]], fill = category)) +
    geom_histogram(binwidth = bin, color = "black", position = "stack") + theme_bw() +
    xlab("Mean Normalized Counts") + ylab("Frequency") +
    scale_x_continuous(breaks = seq(0, xlim, by = 5)) +
    scale_y_continuous(breaks = seq(0, max(counts[[mean]]), by = ytick)) +
    scale_fill_manual(values = fill_colors, name = "Counts") +
    theme(strip.text = element_text(size = 14), axis.text = element_text(size = 12),
          axis.title = element_text(size = 16), legend.title = element_text(size = 14),
          legend.text = element_text(size = 12))
  
  return(plot)
}

skipping_counts <- res.SE.JCEC[, c("SJC_SAMPLE_1", "SJC_SAMPLE_2")]
inclusion_counts <- res.SE.JCEC[, c("IJC_SAMPLE_1", "IJC_SAMPLE_2")]

max(str_count(skipping_counts$SJC_SAMPLE_1, ",") + 1)
max(str_count(skipping_counts$SJC_SAMPLE_2, ",") + 1)

skipping_counts <- skipping_counts %>%
  separate(SJC_SAMPLE_1, into = paste0("SJC_SAMPLE_1_", 1:5), sep = ",", fill = "right", convert = TRUE) %>%
  separate(SJC_SAMPLE_2, into = paste0("SJC_SAMPLE_2_", 1:15), sep = ",", fill = "right", convert = TRUE)
colnames(skipping_counts) <- colnames$label

inclusion_counts <- inclusion_counts %>%
  separate(IJC_SAMPLE_1, into = paste0("IJC_SAMPLE_1_", 1:5), sep = ",", fill = "right", convert = TRUE) %>%
  separate(IJC_SAMPLE_2, into = paste0("IJC_SAMPLE_2_", 1:15), sep = ",", fill = "right", convert = TRUE)
colnames(inclusion_counts) <- colnames$label

skipping_counts$Mean.N <- rowMeans(skipping_counts[, colnames$label[colnames$group == "Normal"]])
skipping_counts$Mean.T <- rowMeans(skipping_counts[, colnames$label[colnames$group == "Tumor"]])
skipping_counts$Mean <- rowMeans(skipping_counts[, colnames$label])
skipping_counts[, c("GeneID", "geneSymbol", "ID")] <- res.SE.JCEC[, c("GeneID", "geneSymbol", "ID")]
rownames(skipping_counts) <- skipping_counts$ID

inclusion_counts$Mean.N <- rowMeans(inclusion_counts[, colnames$label[colnames$group == "Normal"]])
inclusion_counts$Mean.T <- rowMeans(inclusion_counts[, colnames$label[colnames$group == "Tumor"]])
inclusion_counts$Mean <- rowMeans(inclusion_counts[, colnames$label])
inclusion_counts[, c("GeneID", "geneSymbol", "ID")] <- res.SE.JCEC[, c("GeneID", "geneSymbol", "ID")]
rownames(inclusion_counts) <- inclusion_counts$ID

## Plot distributions
nice_Hist(skipping_counts, ytick = 7500) + xlab("Skipping Counts")
nice_Hist(inclusion_counts, , ytick = 1000) + xlab("Inclusion Counts")

# B) Create detectability filter
res.SE.JCEC.det <- res.SE.JCEC.sig[res.SE.JCEC.sig$ID %in% skipping_counts$ID[skipping_counts$Mean > 50], ]
rownames(res.SE.JCEC.det) <- res.SE.JCEC.det$ID
res.SE.JCEC.det$ID <- as.character(res.SE.JCEC.det$ID)

detectable_ids <- c()
for (i in res.SE.JCEC.det$ID) {
  if (res.SE.JCEC.det[i, "IncLevelDifference"] > 0) {
    if (skipping_counts[i, "Mean.T"] > 50) {
      detectable_ids <- c(detectable_ids, i)
    }
  } else if (res.SE.JCEC.det[i, "IncLevelDifference"] < 0) {
    if (skipping_counts[i, "Mean.N"] > 50) {
      detectable_ids <- c(detectable_ids, i)
    }
  }
}

res.SE.JCEC.det <- res.SE.JCEC.det[detectable_ids, ]

write.table(res.SE.JCEC.det[res.SE.JCEC.det$IncLevelDifference > 0, 2:11],
            file = "SE_variants.txt", sep = "\t", row.names = FALSE, col.names = TRUE, quote = FALSE)

```

# 4. Overview of splicing events across samples
```{r}
nice_pie <- function(df, selected_cols = c("typeCol", "freqCol"), colors, order = FALSE, levels = NULL) {
  # Manage data
  pie.df <- df[, selected_cols]
  pie.df$percent <- round(pie.df[, 2]*100/sum(pie.df[, 2]), 1)
  pie.df$label <- paste0(pie.df[, 2], "\n", "(", pie.df$percent, "%)")
  
  if (order) {
    pie.df[, 1] <- factor(pie.df[, 1], levels = levels)
    pie.df <- pie.df[order(pie.df[, 1]), ]
    #pie.df$label <- paste0(pie.df[, 1], "\n", pie.df[, 2], "\n", "(", pie.df$percent, "%)")
  }
  
  # Plot
  p.pie <- ggplot(pie.df, aes(x = "", y = .data[[selected_cols[2]]], fill = .data[[selected_cols[1]]])) +
    geom_bar(stat = "identity", width = 1, color = "white") +
    coord_polar("y", start = 0) +
    theme_void() +
    geom_text(aes(label = label),
              position = position_stack(vjust = 0.5),
              size = 4,
              color = "black") +
    scale_fill_manual(values = colors,
                      labels = c("Alt. 3' Splice Sites (A3SS)", "Alt. 5' Splice Sites (A5SS)",
                                 "Mutually Exclusive Exons (MXE)", "Retained Intron (RI)", "Skipped Exon (SE)")) +
    guides(fill = guide_legend(title = "Splicing Event")) +
    theme(legend.title = element_text(size = 16, face = "bold"),
          legend.text = element_text(size = 14))
  
  return(p.pie)
}
my_colors <- c("#F4F7AE", "#E6BDF4", "#FC9272", "#8E90D8", "#B9F1D6")

summary_all <- data.frame(read.csv("results/all_samples_variable_ind/output/summary.txt", header = TRUE, sep = "\t"))

# Plotting summaries
p.pieJC.tot <- nice_pie(summary_all, selected_cols = c("EventType", "TotalEventsJC"), colors = my_colors) +
  theme(legend.position = "none")
p.pieJC.sig <- nice_pie(summary_all, selected_cols = c("EventType", "SignificantEventsJC"), colors = my_colors)

p.pieJC <- p.pieJC.tot + p.pieJC.sig

p.pieJCEC.tot <- nice_pie(summary_all, selected_cols = c("EventType", "TotalEventsJCEC"), colors = my_colors) +
  theme(legend.position = "none")
p.pieJCEC.sig <- nice_pie(summary_all, selected_cols = c("EventType", "SignificantEventsJCEC"), colors = my_colors)

p.pieJCEC <- p.pieJCEC.tot + p.pieJCEC.sig
```

# 5. Volcano plots
```{r}
cutoff_alpha <- 0.05
cutoff_psi <- 0.1

# Plotting function
volcano_plot <- function(results, x_max = 1, y_max = 6, cutoff_signif = 0.05, cutoff_change = 0.1,
                         signif_var, change_var, label_var, title, colors = c("red", "grey70", "blue"))
{
  # Fixed variables
  sig_nice <- cutoff_signif/5
  chg_nice <- cutoff_change*4
  
  # Manage data
  d.volcano <- data.frame(results)
  d.volcano <- d.volcano[!is.na(d.volcano[, signif_var]) & d.volcano[, signif_var] < 1, ]
  d.volcano[d.volcano[, signif_var] < 10**-y_max, signif_var] <- 10**-y_max
  
  d.volcano$colors <- rep("other", nrow(d.volcano))
  d.volcano$colors[(d.volcano[, change_var] >= cutoff_change & d.volcano[, signif_var] < cutoff_signif)] <- "over"
  d.volcano$colors[(d.volcano[, change_var] <= -cutoff_change & d.volcano[, signif_var] < cutoff_signif)] <- "under"
  
  d.volcano$shapes <- rep("nohits", nrow(d.volcano))
  d.volcano$shapes[d.volcano[, signif_var] <= 10**-y_max] <- "hits"
  
  # Condition for labeling
  cond <- d.volcano[, signif_var] < sig_nice & abs(d.volcano[, change_var]) > chg_nice
  
  # Plot
  p.volcano <- ggplot() + theme_bw() +
    scale_y_continuous(expand = c(0.03, 0),
                       limits = c(0, y_max),
                       breaks = seq(0, y_max, by = 2),
                       minor_breaks = seq(0, y_max, by = 1)) +
    scale_x_continuous(expand = c(0.03, 0.03),
                       limits = c(-x_max, x_max),
                       breaks = seq(-x_max, x_max, by = x_max*0.5),
                       minor_breaks = seq(-x_max, x_max, by = x_max*0.1)) +
    
    # Vertical lines and labels:
    geom_vline(xintercept = c(-cutoff_change, cutoff_change), color = "grey20", alpha = 0.8, linetype = 2, linewidth = 1.2) +
    
    # Horizontal line and label:
    geom_hline(yintercept = -log10(cutoff_signif), color = "grey20", alpha = 0.8, linetype = 2, linewidth = 1.2) +
    geom_text(aes(x = -0.8, y = -log10(cutoff_signif) + 0.15, label = paste("q =", cutoff_signif)), color = "grey20", size = 6.2) +
    
    # Datapoints, in different colors:
    geom_point(data = d.volcano,
               aes(x = .data[[change_var]], y = -log10(.data[[signif_var]]), fill = colors, shape = shapes),
               size = 5.5, color = "gray10", alpha = 0.4, show.legend = TRUE) +
    
    # Color settings
    scale_fill_manual(name = "Splicing change",
                      values = c("over" = colors[1], "other" = colors[2], "under" = colors[3]),
                      breaks = c("over", "other", "under"),
                      labels = c("High in Tumor", "No difference", "High in Normal"),
                      guide = guide_legend(override.aes = aes(shape = 21, size = 3, alpha = 1))) +
    
    # Change outliers shapes
    scale_shape_manual(name = "Shape",
                       values = c("hits" = 24, "nohits" = 21),
                       guide = guide_legend(override.aes = list(fill = "white", size = 3, alpha = 1)),
                       labels = c(bquote(FDR <= 10^-.(y_max)), bquote(FDR > 10^-.(y_max)))) +
    
    # Labels for detectable genes
    geom_label_repel(data = d.volcano[cond, ],
                     aes(x = .data[[change_var]], y = -log10(.data[[signif_var]]), label = .data[[label_var]]),
                     inherit.aes = FALSE, parse = FALSE, max.iter = 5000, color = "black", size = 5,
                     segment.alpha = 1.5, box.padding = unit(0.8, "lines"), min.segment.length = unit(0.01, "lines")) +
    
    # Axis labels:
    labs(x = expression("Δ(PSI)"),
         y = expression("-log"[10]*"(FDR)"),
         title = title) +
    
    # Labels size
    theme(plot.title = element_text(size = 26, hjust = 0.5),
          axis.text.x = element_text(size = 22),
          axis.text.y = element_text(size = 22),
          axis.title.x = element_text(size = 26),
          axis.title.y = element_text(size = 26),
          legend.text = element_text(size = 18),
          legend.title = element_text(size= 20, face = "bold"))
  
  return(p.volcano)
}

# JC model volcanos
pv.SE.JC <- volcano_plot(results = res.SE.JC, signif_var = "FDR", change_var = "IncLevelDifference", label_var = "geneSymbol", title = "Skipped Exon")

pv.MXE.JC <- volcano_plot(results = res.MXE.JC, signif_var = "FDR", change_var = "IncLevelDifference", label_var = "geneSymbol", title = "Mutually Exclusive Exons")

pv.RI.JC <- volcano_plot(results = res.RI.JC, signif_var = "FDR", change_var = "IncLevelDifference", label_var = "geneSymbol", title = "Retained Intron")

pv.A3SS.JC <- volcano_plot(results = res.A3SS.JC, signif_var = "FDR", change_var = "IncLevelDifference", label_var = "geneSymbol", title = "Alt. 3' Splice Sites")

pv.A5SS.JC <- volcano_plot(results = res.A5SS.JC, signif_var = "FDR", change_var = "IncLevelDifference", label_var = "geneSymbol", title = "Alt. 5' Splice Sites")

# JCEC model volcanos
pv.SE.JCEC <- volcano_plot(results = res.SE.JCEC, signif_var = "FDR", change_var = "IncLevelDifference", label_var = "geneSymbol", title = "Skipped Exon")

pv.MXE.JCEC <- volcano_plot(results = res.MXE.JCEC, signif_var = "FDR", change_var = "IncLevelDifference", label_var = "geneSymbol", title = "Mutually Exclusive Exons")

pv.RI.JCEC <- volcano_plot(results = res.RI.JCEC, signif_var = "FDR", change_var = "IncLevelDifference", label_var = "geneSymbol", title = "Retained Intron")

pv.A3SS.JCEC <- volcano_plot(results = res.A3SS.JCEC, signif_var = "FDR", change_var = "IncLevelDifference", label_var = "geneSymbol", title = "Alt. 3' Splice Sites")

pv.A5SS.JCEC <- volcano_plot(results = res.A5SS.JCEC, signif_var = "FDR", change_var = "IncLevelDifference", label_var = "geneSymbol", title = "Alt. 5' Splice Sites")
```

# 6. Heatmaps by splicing event
```{r}
colnames <- data.frame(label = c("51", "57", "59", "63", "148",
                                 "51P", "51-M1", "51-M2", "51-M3", "57M", "59P", "59M",
                                 "62M", "63R", "88-M1", "88-M2", "117M", "123M", "148-P1", "148-P2"),
                       group = c(rep("Normal", 5), rep("Tumor", 15)))

# Colors
ann_colors <- list(Group = c(Normal = "#bbffff", Tumor = "#ffb6c1"))

# Annotation
group_labels <- c(rep("Normal", 5), rep("Tumor", 15))
anot <- data.frame(Group = factor(group_labels))

# Extract psi values
split_psi <- function(df, gene_col = "geneSymbol", psi_cols = c("IncLevel1", "IncLevel2"), num = 10) {
  initial_df <- df[order(df$FDR), ]
  initial_df <- initial_df[1:num, ]
  psi_split <- lapply(initial_df[, psi_cols], function(x) t(sapply(strsplit(x, ","), as.numeric)))
  psi_mat <- do.call(cbind, psi_split)
  rownames(psi_mat) <- initial_df[[gene_col]]
  return(as.data.frame(psi_mat))
}

# Test data frame
mx.SE.JC <- split_psi(res.SE.JC.sig)
mx.SE.JC <- mx.SE.JC[rowSums(is.na(mx.SE.JC)) != ncol(mx.SE.JC), ]
mx.SE.JCEC <- split_psi(res.SE.JCEC.sig)
mx.SE.JCEC <- mx.SE.JCEC[rowSums(is.na(mx.SE.JCEC)) != ncol(mx.SE.JCEC), ]

mx.MXE.JC <- split_psi(res.MXE.JC.sig)
mx.MXE.JC <- mx.MXE.JC[rowSums(is.na(mx.MXE.JC)) != ncol(mx.MXE.JC), ]
mx.MXE.JCEC <- split_psi(res.MXE.JCEC.sig)
mx.MXE.JCEC <- mx.MXE.JCEC[rowSums(is.na(mx.MXE.JCEC)) != ncol(mx.MXE.JCEC), ]

mx.RI.JC <- split_psi(res.RI.JC.sig)
mx.RI.JC <- mx.RI.JC[rowSums(is.na(mx.RI.JC)) != ncol(mx.RI.JC), ]
mx.RI.JCEC <- split_psi(res.RI.JCEC.sig)
mx.RI.JCEC <- mx.RI.JCEC[rowSums(is.na(mx.RI.JCEC)) != ncol(mx.RI.JCEC), ]

mx.A3SS.JC <- split_psi(res.A3SS.JC.sig)
mx.A3SS.JC <- mx.A3SS.JC[rowSums(is.na(mx.A3SS.JC)) != ncol(mx.A3SS.JC), ]
mx.A3SS.JCEC <- split_psi(res.A3SS.JCEC.sig)
mx.A3SS.JCEC <- mx.A3SS.JCEC[rowSums(is.na(mx.A3SS.JCEC)) != ncol(mx.A3SS.JCEC), ]

mx.A5SS.JC <- split_psi(res.A5SS.JC.sig)
mx.A5SS.JC <- mx.A5SS.JC[rowSums(is.na(mx.A5SS.JC)) != ncol(mx.A5SS.JC), ]
mx.A5SS.JCEC <- split_psi(res.A5SS.JCEC.sig)
mx.A5SS.JCEC <- mx.A5SS.JCEC[rowSums(is.na(mx.A5SS.JCEC)) != ncol(mx.A5SS.JCEC), ]

mx.JC.merged <- rbind(mx.SE.JC, mx.MXE.JC, mx.RI.JC, mx.A3SS.JC, mx.A5SS.JC)
mx.JCEC.merged <- rbind(mx.SE.JCEC, mx.MXE.JCEC, mx.RI.JCEC, mx.A3SS.JCEC, mx.A5SS.JCEC)
colnames(mx.JC.merged) <- colnames$label
colnames(mx.JCEC.merged) <- colnames$label

# Plot heatmap
plot_heatmap <- function(df, annotation = anot, annotation_cols = ann_colors) {
  psi_scaled <- t(scale(t(df)))
  rownames(annotation) <- colnames(psi_scaled)
  
  p.heat <- pheatmap(psi_scaled,
                     cluster_cols = FALSE,
                     cluster_rows = FALSE,
                     show_rownames = TRUE, 
                     scale = "none",
                     gaps_row = c(10, 20, 30, 40),
                     gaps_col = c(5),
                     annotation_col = annotation,
                     annotation_colors = annotation_cols,
                     fontsize_row = 8,
                     show_colnames = TRUE)
  
  return(p.heat)
}

ph.JC.merged <- plot_heatmap(mx.JC.merged)
ph.JCEC.merged <- plot_heatmap(mx.JCEC.merged)
```

# 7. [IN PROGRESS] Barplots per gene with splicing events
```{r}
count_shared_events <- function(df, psi_col, group) {
  # Split and convert PSI strings to numeric vectors
  psi_matrix <- t(sapply(strsplit(df[[psi_col]], ","), as.numeric))
  psi_df <- as.data.frame(psi_matrix)
  
  # Assign consistent sample names
  colnames(psi_df) <- paste(group, seq_len(ncol(psi_df)), sep = "_")
  
  # Bind gene symbol and event ID (optional)
  psi_df$geneSymbol <- df$geneSymbol
  psi_df$eventID <- seq_len(nrow(df))  # to track unique splicing events if needed
  
  # Count number of non-NA & non-zero PSI values per event (row)
  count_df <- psi_df[, 1:(ncol(psi_df) - 2)]  # exclude geneSymbol and eventID
  non_zero_counts <- rowSums(!is.na(count_df) & count_df > 0)
  
  # Create frequency table
  frequency_table <- table(non_zero_counts)
  
  return(list(table = frequency_table, matrix = psi_df))
}


```
